# Generated by Django 5.2.4 on 2025-12-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Username контакта в Telegram (без @) для уведомлений', max_length=255, null=True, verbose_name='Telegram Username'),
        ),
    ]
