# Generated by Django 5.2.4 on 2026-01-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_emergencycontact_telegram_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='telegram_username',
        ),
    ]
