# Generated by Django 5.2.4 on 2025-12-09 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geozone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Zone Name')),
                ('description', models.TextField(blank=True)),
                ('zone_type', models.CharField(choices=[('safe', 'Safe Zone'), ('dangerous', 'Dangerous Zone'), ('custom', 'Custom Zone')], default='safe', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius', models.FloatField(help_text='Radius in meters')),
                ('polygon_coordinates', models.JSONField(blank=True, help_text='Array of [lat, lng] coordinates', null=True)),
                ('notify_on_enter', models.BooleanField(default=True)),
                ('notify_on_exit', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emergency_contacts', models.ManyToManyField(blank=True, related_name='geozones', to='contacts.emergencycontact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geozones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geozone',
                'verbose_name_plural': 'Geozones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SharedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(max_length=64, unique=True)),
                ('duration_minutes', models.IntegerField(help_text='Duration of sharing in minutes')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.emergencycontact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared Location',
                'verbose_name_plural': 'Shared Locations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeozoneEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enter', 'Entered Zone'), ('exit', 'Exited Zone')], max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('notification_sent', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('geozone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='geolocation.geozone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geozone Event',
                'verbose_name_plural': 'Geozone Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='geolocation_user_id_584aff_idx'), models.Index(fields=['geozone', '-timestamp'], name='geolocation_geozone_44a013_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(help_text='Location accuracy in meters')),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in m/s', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Heading in degrees', null=True)),
                ('address', models.TextField(blank=True)),
                ('activity_type', models.CharField(blank=True, choices=[('stationary', 'Stationary'), ('walking', 'Walking'), ('running', 'Running'), ('driving', 'Driving')], max_length=50)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location History',
                'verbose_name_plural': 'Location Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='geolocation_user_id_263c56_idx'), models.Index(fields=['-timestamp'], name='geolocation_timesta_297787_idx')],
            },
        ),
    ]
