# Generated by Django 5.2.4 on 2025-12-16 02:58

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Ваш @username в Telegram (без @). Используется для SOS уведомлений.', max_length=255, null=True, verbose_name='Telegram Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Формат: +996XXXXXXXXX', max_length=128, region=None, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Автоматически генерируется, не используется пользователем', max_length=150, null=True, unique=True),
        ),
    ]
