# Generated by Django 5.2.4 on 2025-12-09 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='active', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_accuracy', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('map_link', models.URLField(blank=True, max_length=500)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sos/audio/%Y/%m/%d/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='sos/video/%Y/%m/%d/')),
                ('activation_method', models.CharField(choices=[('button', 'Button Press'), ('slider', 'Slider'), ('voice', 'Voice Command'), ('timer', 'Timer Expiry')], default='button', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOS Alert',
                'verbose_name_plural': 'SOS Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.IntegerField(verbose_name='Duration (minutes)')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('check_in_message', models.TextField(blank=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_timers', to=settings.AUTH_USER_MODEL)),
                ('sos_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timer_alerts', to='sos.sosalert')),
            ],
            options={
                'verbose_name': 'Activity Timer',
                'verbose_name_plural': 'Activity Timers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sms', 'SMS'), ('push', 'Push Notification'), ('email', 'Email')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20)),
                ('content', models.TextField()),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.emergencycontact')),
                ('sos_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sos.sosalert')),
            ],
            options={
                'verbose_name': 'SOS Notification',
                'verbose_name_plural': 'SOS Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['-created_at'], name='sos_sosaler_created_6f01b3_idx'),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['user', 'status'], name='sos_sosaler_user_id_caad79_idx'),
        ),
    ]
