# Generated by Django 5.2.4 on 2026-01-11 07:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosalert',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='sosnotification',
            name='notification_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('push', 'Push Notification'), ('email', 'Email'), ('telegram', 'Telegram')], max_length=10),
        ),
    ]
