# Generated by Django 5.2.4 on 2026-01-11 07:49

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_alter_sosalert_audio_file_alter_sosalert_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosalert',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='sos/audio/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='sos/video/%Y/%m/%d/'),
        ),
    ]
