# Generated by Django 5.2.4 on 2025-12-31 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_activationcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcode',
            name='activated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_codes', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddIndex(
            model_name='activationcode',
            index=models.Index(fields=['code', 'is_active'], name='subscriptio_code_a8b8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='activationcode',
            index=models.Index(fields=['is_used', 'expires_at'], name='subscriptio_is_used_fe2c39_idx'),
        ),
    ]
