# Generated by Django 5.2.4 on 2026-01-22 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_activationcode_activated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_telegram_ids', models.TextField(default='', help_text='Telegram User IDs админов через запятую (например: 123456789,987654321)')),
                ('test_mode_enabled', models.BooleanField(default=False, help_text='Включить тестовый режим для всех пользователей')),
                ('default_price_stars', models.IntegerField(default=100, help_text='Цена по умолчанию в Telegram Stars')),
                ('subscription_days', models.IntegerField(default=30, help_text='Количество дней подписки')),
                ('code_expiration_hours', models.IntegerField(default=24, help_text='Срок действия кода активации в часах')),
                ('total_payments_received', models.IntegerField(default=0)),
                ('total_codes_generated', models.IntegerField(default=0)),
                ('total_codes_activated', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Settings',
                'verbose_name_plural': 'Bot Settings',
            },
        ),
        migrations.AddField(
            model_name='activationcode',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, help_text='Тестовый код для админа'),
        ),
        migrations.AddField(
            model_name='activationcode',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_codes', to='subscriptions.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='telegram_payment_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_stars',
            field=models.IntegerField(default=100, help_text='Цена подписки в Telegram Stars', verbose_name='Price in Telegram Stars'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('mobile_o', 'O!'), ('mobile_mega', 'MegaCom'), ('mobile_beeline', 'Beeline'), ('card', 'Bank Card'), ('telegram_stars', 'Telegram Stars')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='activationcode',
            index=models.Index(fields=['is_test', 'telegram_user_id'], name='subscriptio_is_test_88c0b5_idx'),
        ),
    ]
