# Generated by Django 5.2.4 on 2025-12-31 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('sos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSMediaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField()),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('upload_status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('media_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('sos_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_logs', to='sos.sosalert')),
            ],
            options={
                'verbose_name': 'SOS Media Log',
                'verbose_name_plural': 'SOS Media Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('sos_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='sos.sosalert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Access Token',
                'verbose_name_plural': 'Media Access Tokens',
                'indexes': [models.Index(fields=['token', 'expires_at'], name='notificatio_token_f05f19_idx')],
            },
        ),
    ]
